### ISSUE TITLE
Trying to run this code in core php

### ISSUE THREAD

**Issue by mrabd423** [giggsey/libphonenumber-for-php#150]
Hi to all.
I'm just trying to run the code as you have explained about this api but i'm getting error of Class not found. What should i do?

**Comment by giggsey** [comment]
Do you have any code examples of what you are trying to execute, and the error you are getting?

**Comment by mrabd423** [comment]
index.php is my file.


*Fatal error*: Class 'libphonenumber\PhoneNumberUtil' not found in
*C:\xampp\htdocs\validate_phone\libphonenumber-for-php-master\index.php* on
line *4*

<?php

$swissNumberStr = "044 668 18 00";
$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
try {
    $swissNumberProto = $phoneUtil->parse($swissNumberStr, "CH");
    var_dump($swissNumberProto);
} catch (\libphonenumber\NumberParseException $e) {
    var_dump($e);
}


[image: Inline image 1]

**Comment by giggsey** [comment]
You need to use an autoloader so the PHP files are loaded.

If you are using libphonenumber-for-php v8, then it needs to be PSR-4 compatible, otherwise a PSR-0 autoloader will do.

I recommend using [Composer](https://getcomposer.org/doc/00-intro.md) to handle this for you.

**Comment by LunarDevelopment** [comment]
I'm getting similar issues on this too, I'm using composer and the psr 4 namespacing is in place 
```php 
    'libphonenumber\\' => array($vendorDir . '/giggsey/libphonenumber-for-php/src'),
```
but it seems like the classes that I haven't directly instantiated e.g. 
```php 
    $PhoneNumberToCarrierMapper =  \libphonenumber\PhoneNumberToCarrierMapper::getInstance();
``` 
can't see each other, when I run code with the above it works then fails with the following:
```CLI
Fatal error: Uncaught Error: Class 'libphonenumber\PhoneNumber' not found in C:\Development\crb_scan_tom\pthreads\vendor\giggsey\libphonenumber-for-php\src\PhoneNumberUtil.php:2781
Stack trace:
#0 C:\Development\crb_scan_tom\pthreads\TelephoneValidator.php(138): libphonenumber\PhoneNumberUtil->parse('+441132322700', 'gb', NULL, true)
#1 [internal function]: T->run()
#2 {main}
  thrown in C:\Development\crb_scan_tom\pthreads\vendor\giggsey\libphonenumber-for-php\src\PhoneNumberUtil.php on line 2781
``` 

after getting the above I then manually instantiated the "not found" class `PhoneNumber` and I then got the following, it seems like Icould be on all day manually instantiating all the classes that their siblings can't instantiate themselves : 
```CLI

C:\Development\crb_scan_tom\pthreads>php TelephoneValidator.php
PHP Fatal error:  Uncaught Error: Class 'libphonenumber\CountryCodeSource' not found in C:\Development\crb_scan_tom\pthreads\vendor\giggsey\libphonenumber-for-php\src\PhoneNumberUtil.php:1773
Stack trace:
```

**Comment by giggsey** [comment]
@LunarDevelopment Are you actually using a PSR-4 autoloader there? Or if you are using composer, are you loading the 'vendor/autoload.php'?

**Comment by LunarDevelopment** [comment]
I am using: 
```php
require 'vendor/autoload.php';
```

**Comment by giggsey** [comment]
@LunarDevelopment That should be working fine.

Can you provide a code sample and your composer.json so I can attempt to reproduce?

**Comment by LunarDevelopment** [comment]
My code is a bit complicated at the min as it's linking to a database to
get and update phone numbers and the whole thing is wrapped in pthreads.

I'll continue to investigate and post back when I crack it.

Probably something to do with namespacing and I'm missing it..

**Comment by giggsey** [comment]
As there hasn't been any feedback from @mrabd423, I'm closing this issue. If you have this issue again, please reopen.

@LunarDevelopment If you are able to reproduce the error, can you open a new issue.

**Comment by Appiah** [comment]
Having this in my php error log : 

PHP Fatal error:  Class 'libphonenumber\CountryCodeToRegionCodeMap' not found in /Applications/MAMP/htdocs/libphonenumber/PhoneNumberUtil.php on line 374

Have done all the above suggestions but still no luck yet.

I need to work for my phase on of what we are trying to do with / in aireceive.

Would appreciate any help. Cheers Gig.

**Comment by giggsey** [comment]
@Appiah Are you using an autoloader?

**Comment by Appiah** [comment]
Hi Joshua Gig, Thanks for getting back to me this quickly.

No, am not using autoloader. A link to know more on autoloaders
for php, if any,  would also be much appreciated.

Meanwhile, after a few considerations, I decided to rather stick
with the java side of libphonenumber for now. And it is working
fine for now.

More on the project at : 
https://github.com/Appiah/aireceive_phone_num_cleaning_project

Once again, thanks, you are such an inspiration to me.

I salute you.

**Comment by giggsey** [comment]
For future reference, instructions on the requirements of this project can
be found in the README file. This includes details about using an
autoloader.

Also, it's Gigg/giggsey (two g's) :)

**Comment by Appiah** [comment]
ok. thanks.

**Comment by OptimusV7** [comment]
added   require_once './vendor/autoload.php'; in my controller that had the code with error
FYI this is in a codeiginter project
